AWSTemplateFormatVersion: "2010-09-09"
Description: "YMAL string"
# --------------------------------------------------------------------------------------
#- Author: Brian Keith
#- Date: 14 Nov 2019
#- Name: Udemy RDS Course Security Groups CF.yml
#- Description: Add security groups and rules
#- Version: 0.1
#- Purpose: Requires Udemy RDS Course VPC CF.yml stack. Imports VPC and other values
#----------------------------------------------------------------------------------------- 

# Metadata: 

Parameters:
  NetworkStackName:
    Description: >-
      Name of an active CloudFormation stack that contains the networking
      resources, such as the VPC and subnets, that will be used in
      this stack.
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: '^[a-zA-Z][-a-zA-Z0-9]*$'
    Default: UdemyRDSNetwork

# Mappings: 

# Conditions: 

# Transform: 

Resources: 

#RDS Security Group
  sgRDSsecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: Allow traffice to RDS instances
        VpcId:
          "Fn::ImportValue": 
            "Fn::Sub": "${NetworkStackName}-MyRDS-VPCID"
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 1521
          ToPort: 1521
          CidrIp: 0.0.0.0/0
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 1433
          ToPort: 1433
          CidrIp: 0.0.0.0/0
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
        # SecurityGroupEgress:
        # - IpProtocol: tcp
        #   FromPort: -1
        #   ToPort: -1
        #   CidrIp: 0.0.0.0/0

# Outputs: 