AWSTemplateFormatVersion: "2010-09-09"
Description: "VPC Networking CloudFormation Template"
# --------------------------------------------------------------------------------------
#- Author: Brian Keith
#- Date: 13 NOV 2019
#- Name:Udemy RDS Course VPC CF.yml
#- Description: Creates the VPC and related networking resources
#- Version: 0.1
#- Purpose: The template is used with Udemy RDS course. Creates VPC with subnets and components
#----------------------------------------------------------------------------------------- 

# Metadata: 

# Parameters:
  # varRegion: us-west-2 

# Mappings: 

# Conditions: 

# Transform: 

Resources: 
#CREATE VPC
  myRDSVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'false'
      EnableDnsHostnames: 'false'
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: myRDSVPC
        - Key: FTSArchitect
          Value: 'Brian Keith'
        - Key: Purpose
          Value: 'Build a VPC for RDS course'

#CREATE SUBNETS
  subPublic2a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: myRDSVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: "us-west-2a"
      Tags:
      - Key: Name
        Value: subRDSPublic2a

  subPublic2b:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: myRDSVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: "us-west-2b"
      Tags:
      - Key: Name
        Value: subRDSPublic2b
  
  subPrivate2a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: myRDSVPC
      CidrBlock: 10.0.10.0/24
      AvailabilityZone: "us-west-2a"
      Tags:
      - Key: Name
        Value: subRDSPrivate2a

  subPrivate2b:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: myRDSVPC
      CidrBlock: 10.0.20.0/24
      AvailabilityZone: "us-west-2b"
      Tags:
      - Key: Name
        Value: subRDSPrivate2b 

#CREATE INTERNET GATEWAY
  igwInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: igwInternetGateway
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: myRDSVPC
      InternetGatewayId:
        Ref: igwInternetGateway 

#CREATE PUBLIC ROUTE TABLE and ROUTES
  rtbPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: myRDSVPC
      Tags:
      - Key: Name
        Value: rtbPublicRouteTable

  myPubRoute:
    Type: AWS::EC2::Route
    #DependsOn: GatewayToInternet
    Properties:
       RouteTableId:
         Ref: rtbPublicRouteTable
       DestinationCidrBlock: 0.0.0.0/0
       GatewayId:
         Ref: igwInternetGateway

  mySubnetRouteTableAssociationPublic2a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: subPublic2a
      RouteTableId:
        Ref: rtbPublicRouteTable

  mySubnetRouteTableAssociationPublic2b:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: subPublic2b
      RouteTableId:
        Ref: rtbPublicRouteTable

#CREATE PRIVATE ROUTE TABLE AND ROUTES
  rtbPrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: myRDSVPC
      Tags:
      - Key: Name
        Value: rtbPrivateRouteTable

  mySubnetRouteTableAssociationPrivate2a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: subPrivate2a
      RouteTableId:
        Ref: rtbPrivateRouteTable

  mySubnetRouteTableAssociationPrivate2b:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: subPrivate2b
      RouteTableId:
        Ref: rtbPrivateRouteTable


#CREATE ACLs for PUBLIC and PRIVATE SUBNETS
  aclPublicSubs:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId:
        Ref: myRDSVPC
      Tags:
        - Key: Name
          Value: aclPublicSubs

  myPublic2aSubnetNetworkAclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId:
        Ref: subPublic2a
      NetworkAclId:
        Ref: aclPublicSubs
  myPublic2bSubnetNetworkAclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId:
        Ref: subPublic2b
      NetworkAclId:
        Ref: aclPublicSubs

  myNetworkAclEntryEgr:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId:
        Ref: aclPublicSubs
      RuleNumber: '100'
      Protocol: "-1"
      RuleAction: allow
      Egress: 'true'
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: '-1'
        To: '-1'

  myNetworkAclEntryIgr:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId:
        Ref: aclPublicSubs
      RuleNumber: '100'
      Protocol: "-1"
      RuleAction: allow
      Egress: 'false'
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: '-1'
        To: '-1'

  aclPrivateSubs:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId:
        Ref: myRDSVPC
      Tags:
        - Key: Name
          Value: aclPrivateSubs

  myPrivate2aSubnetNetworkAclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId:
        Ref: subPrivate2a
      NetworkAclId:
        Ref: aclPrivateSubs
  myPrivate2bSubnetNetworkAclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId:
        Ref: subPrivate2b
      NetworkAclId:
        Ref: aclPrivateSubs


#OUTPUTS
Outputs:
  StackVPC:
    Description: 'The ID of the VPC'
    Value: !Ref myRDSVPC
    Export:
      Name: !Sub "${AWS::StackName}-MyRDS-VPCID"
  
  PublicSub2a:
    Description: 'The ID of the Public Subnet 2a'
    Value: !Ref subPublic2a
    Export: 
      Name: !Sub "${AWS::StackName}-Pubsubnet2a"

  PublicSub2b:
    Description: 'The ID of the Public Subnet 2b'
    Value: !Ref subPublic2b
    Export: 
      Name: !Sub "${AWS::StackName}-Pubsubnet2b"

  PrivateSub2a:
    Description: 'The ID of the Private Subnet 2a'
    Value: !Ref subPrivate2a
    Export: 
      Name: !Sub "${AWS::StackName}-Privatesubnet2a"

  PrivateSub2b:
    Description: 'The ID of the Private Subnet 2b'
    Value: !Ref subPrivate2b
    Export: 
      Name: !Sub "${AWS::StackName}-Privatesubnet2b"

  aclPublicSubs:
    Description: 'The ID of the Public Subnets ACL'
    Value: !Ref aclPublicSubs
    Export:
      Name: !Sub "${AWS::StackName}-aclPublicSubs"

  aclPrivateSubs:
    Description: 'The ID of the Private Subnets ACL'
    Value: !Ref aclPrivateSubs
    Export:
      Name: !Sub "${AWS::StackName}-aclPrivateSubs"